name: Delete File on Push

on: 
  push:
    branches:
      - main  # Specify the branch you want to trigger the action on

jobs:
  delete_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Delete file if it exists
        run: |
          if [ -f "st.ps1" ]; then
            git rm "st.ps1"
            git commit -m "Remove file.txt if it exists"
            git push
          else
            echo "File does not exist."
          fi
