name: Remove st.ps1 if included in a Push

on:
  push:
    branches:
      - '**'

jobs:
  check-and-delete-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check if st.ps1 exists
      id: check_existence
      run: |
        if [ -f "st.ps1" ]; then
          echo "st_exists=true" >> $GITHUB_OUTPUT
        else
          echo "st_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Delete st.ps1 if it exists
      if: steps.check_existence.outputs.st_exists == 'true'
      run: |
        git config --global user.email "emadadel4-action@noreply.github.com"
        git config --global user.name "emadadel4-action"
        git rm st.ps1
        git commit -m "Delete st.ps1 as it is not allowed"
        git push origin HEAD:${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}